### ISSUE TITLE
导入私钥有问题

### ISSUE THREAD

**Issue by ywss** [NianJi/BBRSACryptor#1]
导入私钥有问题

**Comment by NianJi** [comment]
这个是有问题，因为没有规定证书的格式，当时写的时候格式刚好适合自己的场景，所以就这样写了。

**Comment by eiji110007** [comment]
你好，我也是导入公钥和私钥的时候有问题。这个应该怎么解决啊？我是pem读出来导进去的，求指教，谢谢

**Comment by NianJi** [comment]
see [#2](https://github.com/NianJi/BBRSACryptor/issues/2)
