### ISSUE TITLE
请问关于公钥解密的问题

### ISSUE THREAD

**Issue by Kejiasir** [NianJi/BBRSACryptor#4]
你好, 我们Java后台返回rsa加密后字符串, 同时返回PublicKey字符串需要对前面的字符串进行解密,  按照你的demo使用方法解密出来是空的, 请问是什么原因呢?

**Comment by Kejiasir** [comment]
对了, 加载公钥使用的是 - (BOOL)importRSAPublicKeyBase64:(NSString *)publicKey 这个标记为过时的方法, 和这个方式加载有关系吗?

**Comment by NianJi** [comment]
原因应该是证书的格式不匹配，你可以直接让服务端把证书给你，PEM或 DER格式的都可以。然后按我readme的方式加载

**Comment by Kejiasir** [comment]
好的, 谢谢你的解答
