### ISSUE TITLE
公钥加密错误

### ISSUE THREAD

**Issue by longxdragon** [NianJi/BBRSACryptor#5]
需要加密的内容：
accessToken=8563fd00a4bcf5f0f3e95003d450278b15127d3a065f6486&uuid=00BD9E15-141F-4788-9EA2-4085DDB7FB14&encript_key=PMZJIWWQKTIUGPIENLOWWOMW

加密后：
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

这是什么原因？是因为加密的内容里有特殊的字符？

**Comment by longxdragon** [comment]
是不是不支持分段加密？

**Comment by NianJi** [comment]
目前不支持分段加密，但是你这个长度应该还没有超出限制。把加密代码发我下试试

**Comment by longxdragon** [comment]
公钥长度是128，加密的内容是138。。。

BBRSACryptor *rsaCryptor = [[BBRSACryptor alloc] init];
    [rsaCryptor importRSAPublicKeyBase64:kRSAPublicKey];
    NSData *safeData = [rsaCryptor encryptWithPublicKeyUsingPadding:RSA_PKCS1_PADDING plainData:[paramStr dataUsingEncoding:NSUTF8StringEncoding]];
    NSString *safetyStr = [GTMBase64 stringByEncodingData:safeData];

**Comment by longxdragon** [comment]
是分段加密的问题，扩展支持分段加密就可以了

**Comment by NianJi** [comment]
好的，如果你有兴趣，可以帮这个库支持下分段加密，可以提pull request给我.
