### ISSUE TITLE
PEM_read_bio_RSA_PUBKEY leaks 内存泄露

### ISSUE THREAD

**Issue by longxdragon** [NianJi/BBRSACryptor#7]
用leaks检测，一直提示内存泄露。。。求解

**Comment by longxdragon** [comment]
![image](https://cloud.githubusercontent.com/assets/3031559/25602935/2103c506-2f2a-11e7-8fd7-7254140ead00.png)

**Comment by NianJi** [comment]
是不是这个方法多次调用了？第二次调用的时候没有把第一次的_rsaPublic释放。可以在赋值前加个判断，如果_rsaPublic不为null,先释放一下。

**Comment by longxdragon** [comment]
对的，测试的时候调用了多次，我试试

**Comment by longxdragon** [comment]
改成局部变量后，RSA_free()释放RSA对象，好像可以解决这个问题

**Comment by NianJi** [comment]
fix: 169d6dc3000ebe458605608d29593554144116fe
